import { Button } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';
import { useCallback, useEffect, useRef } from 'react';
import useSWR from 'swr';

import { Response } from './api/restaurants';

const Home: NextPage = () => {
  const { data } = useSWR<Response>('/api/restaurants');

  const mapRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    console.log(111, window);

    const naver = (window as any).naver;

    console.log(222, naver);
  }, []);

  const handleLoadNaver = useCallback(() => {
    console.log('handleLoadNaver', window.naver);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NAVER_CLIENT_ID}`}
        onLoad={handleLoadNaver}
      ></Script>
      <main>
        {data?.data.length}
        <div
          id="map"
          style={{
            width: 400,
            height: 400,
          }}
        ></div>
        <Button variant="contained">Hello World</Button>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};

export default Home;
